### PR TITLE
solution

### PR DESCRIPTION
**Pull request by Andrey1104**

### CODE REVIEW

**Review by viktoria-rybenchuk — CHANGES_REQUESTED** [review]
All test should passed

**Comment by Andrey1104** [comment]
I dont understend why test not passed. need help

**Comment by Andrey1104** [comment]
most intresting, this test passed in one go

**Review by viktoria-rybenchuk — CHANGES_REQUESTED** [review]
you can see logs in checks
Screenshot from 2023-11-26 20-28-44

**Review by viktoria-rybenchuk — CHANGES_REQUESTED** [review]
Screenshot from 2023-11-26 20-40-42

**Comment by Andrey1104** [comment]
як я зрозумів проблема в порядку отриманого кверісету order.objects.all()

**Review by Polyakiv-Andrey — APPROVED** [review]
Good job!

**Pull request closed without merging**
